//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control8.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int Id { get; set; }
        public System.DateTime DateEvent { get; set; }
        public int IdGroup { get; set; }
        public int IdActivity { get; set; }
        public decimal Mark { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Group Group { get; set; }
    }
}
